# Generated by Django 2.0 on 2017-12-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('usermail', models.EmailField(max_length=20)),
                ('userpass', models.CharField(max_length=20)),
            ],
        ),
    ]
