# Generated by Django 2.0 on 2018-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180103_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usermail',
            field=models.EmailField(max_length=25),
        ),
    ]
