# Generated by Django 2.0 on 2018-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
