# Generated by Django 2.0 on 2018-01-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180105_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content1',
            new_name='content_title',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content4',
        ),
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Title'),
        ),
    ]
