# Generated by Django 2.0 on 2018-01-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180105_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
