# Generated by Django 2.0 on 2018-01-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_content_content_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='title',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
