# Generated by Django 2.0 on 2018-01-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180105_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(null=True)),
                ('content_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Title')),
            ],
        ),
    ]
