# Generated by Django 2.0 on 2018-01-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='link_href',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
