# Generated by Django 2.0 on 2018-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_content_link_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='link_href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
